backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
media_folder: "_site/assets/images"
public_folder: "/assets/images"

collections:
  - name: "letter-a"
    label: "name starting with the Letter A"
    folder: "src/names/letter-a"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["a"] }

  - name: "letter-b"
    label: "name starting with the Letter B"
    folder: "src/names/letter-b"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["b"] }

  - name: "letter-c"
    label: "name starting with the Letter C"
    folder: "src/names/letter-c"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "title", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["c"] }

  - name: "letter-d"
    label: "name starting with the Letter D"
    folder: "src/names/letter-d"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["d"] }

  - name: "letter-e"
    label: "name starting with the Letter E"
    folder: "src/names/letter-e"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["e"] }

  - name: "letter-f"
    label: "name starting with the Letter F"
    folder: "src/names/letter-f"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["f"] }

  - name: "letter-g"
    label: "name starting with the Letter G"
    folder: "src/names/letter-g"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["g"] }

  - name: "letter-h"
    label: "name starting with the Letter H"
    folder: "src/names/letter-h"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["h"] }

  - name: "letter-i"
    label: "name starting with the Letter I"
    folder: "src/names/letter-i"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["i"] }

  - name: "letter-j"
    label: "name starting with the Letter J"
    folder: "src/names/letter-j"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["j"] }

  - name: "letter-k"
    label: "name starting with the Letter K"
    folder: "src/names/letter-k"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["k"] }

  - name: "letter-l"
    label: "name starting with the Letter L"
    folder: "src/names/letter-l"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["l"] }

  - name: "letter-m"
    label: "name starting with the Letter M"
    folder: "src/names/letter-m"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["m"] }

  - name: "letter-n"
    label: "name starting with the Letter N"
    folder: "src/names/letter-n"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["n"] }

  - name: "letter-o"
    label: "name starting with the Letter O"
    folder: "src/names/letter-o"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["o"] }

  - name: "letter-p"
    label: "name starting with the Letter P"
    folder: "src/names/letter-p"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["p"] }

  - name: "letter-q"
    label: "name starting with the Letter Q"
    folder: "src/names/letter-q"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["q"] }

  - name: "letter-r"
    label: "name starting with the Letter R"
    folder: "src/names/letter-r"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["r"] }

  - name: "letter-s"
    label: "name starting with the Letter S"
    folder: "src/names/letter-s"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["s"] }

  - name: "letter-t"
    label: "name starting with the Letter T"
    folder: "src/names/letter-t"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["t"] }

  - name: "letter-u"
    label: "name starting with the Letter U"
    folder: "src/names/letter-u"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["u"] }

  - name: "letter-v"
    label: "name starting with the Letter V"
    folder: "src/names/letter-v"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["v"] }

  - name: "letter-w"
    label: "name starting with the Letter W"
    folder: "src/names/letter-w"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["w"] }

  - name: "letter-x"
    label: "name starting with the Letter X"
    folder: "src/names/letter-x"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["x"] }

  - name: "letter-y"
    label: "name starting with the Letter Y"
    folder: "src/names/letter-y"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["y"] }

  - name: "letter-z"
    label: "name starting with the Letter Z"
    folder: "src/names/letter-z"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Description/ Meaning/ Cultural significance",
          name: "description",
          widget: "string",
        }
      - { label: "Language(s)", name: "language", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["z"] }
